desktop/package.json
desktop/src/components/forms/Project/project.js
desktop/src/components/tables/SortSelect/sortSelectTable.js
desktop/src/components/tables/VirtualizedSortSelect/cell.js
desktop/src/helpers/time.js
desktop/src/store/Export/actions.js
desktop/src/store/User/actions.js

This branch is focused on improving the data export system.
* Fixed Date formatting for tables in excel and in the analyze section
* Fixed the time parsing for overtime shifts in the analyze section
* One error with a depreciated componentWillMount method

Export notifications

---

database/v3/translation/translate.js
desktop/package.json
desktop/src/components/tables/Generic/genericTable.js
desktop/src/components/tables/SortSelect/sortSelectTable.js
desktop/src/components/tables/VirtualizedSortSelect/cell.js
desktop/src/components/tables/VirtualizedSortSelect/virtualizedSortSelect.js
desktop/src/containers/Analyze/projectDetailContainer.js
desktop/src/containers/Analyze/shiftDetailsContainer.js
desktop/src/containers/Analyze/shiftIndexContainer.js
desktop/src/containers/Clock/clockOutContainer.js
desktop/src/helpers/__tests__/time.test.js
desktop/src/helpers/time.js
desktop/src/setupTests.js
desktop/src/store/Employee/actions.js

There were numerous problems occurring with dates. Loopback automatically takes date times you give it and converts them to UTC. I was unaware of this, but this is the fix in both the frontend and the database translation script.
* One error with a depreciated componentWillMount method

Local Time to UTC Time Project Conversion

---

database/v3/translation/translate.js
desktop/package.json
desktop/public/electron.js
desktop/src/components/forms/AccountAction/accountAction.js
desktop/src/components/forms/AccountSigin/accountSigin.js
desktop/src/components/forms/Shift/Filter/filter.js
desktop/src/constants/ipc.js
desktop/src/constants/settings.js
desktop/src/containers/Account/accountActionContainer.js
desktop/src/containers/Account/accountSigninContainer.js
desktop/src/containers/Shift/shiftFilter.container.js
desktop/src/electron-starter.js
desktop/src/store/Employee/actions.js
desktop/src/store/Employee/endpoints.js
desktop/src/store/User/endpoints.js
desktop/yarn.lock

Predeploy Tweaks

---

desktop/public/electron.js

update electron file to load devtools unless is dev

---

desktop/package.json
desktop/src/components/tables/Table/cells/projectCell.js
desktop/src/components/tables/Table/cells/taskCell.js

Fix null exceptions from parts of shifts being rendered in shiftIndex

fix: null checking activities in project and task cells

---

desktop/package.json
desktop/src/components/forms/Project/projectEdit.js
desktop/src/containers/Project/projectCRUD.container.js
desktop/src/containers/Project/projectEdit.container.js
desktop/src/scenes/Analyze/analyze.js

Recent shifts button in project section

---

api/common/models/project.js

wip: fix api server

---

desktop/package.json
desktop/pnpm-lock.yaml
desktop/src/components/forms/Employee/employee.jsx

feat: create password generator button

---

desktop/src/components/forms/Employee/employee.jsx

fix: fixed button color for employee pin generator

---

desktop/src/containers/Auth/authSigninContainer.jsx

-Fixed the issue of auth screen flashing when loading the Formik numpad upon login. 
-Now, there is a loading spinner in the loading state instead.
-In addition, the code was rewritten from class component into a functional component.

fix: loading spinner instead of auth screen flash

---

api/lb3app/common/models/employee.js
desktop/src/store/Shift/selectors.jsx
desktop/src/store/employee.ts

Clockout uses the last shift based on insert order in the database not based on time of the shift. 
With this code, employee clockout will bring up the most recent (timewise) half-shift that the employee has.

fix: clockout most recent half shift

---

desktop/src/components/forms/Shift/HalfShift/halfShift.jsx
desktop/src/containers/Shift/shiftCRUD.container.jsx
desktop/src/store/Shift/actions.js
desktop/src/store/Shift/endpoints.js

This code prevents a user from adding a half-shift if this user already has a half-shift running. Appropriate error message pops up below Employee if attempted.
[Screencast from 04-28-2024 06:56:29 PM.webm](https://github.com/joshuawootonn/time-track/assets/68671029/607fce86-564e-46e0-96ea-eb3824ab3bdc)
[Screencast from 04-28-2024 06:54:52 PM.webm](https://github.com/joshuawootonn/time-track/assets/68671029/e1f2a9c8-0993-4a8c-976a-a6c48ae517e1)

fix: prevent extra half shift

---

desktop/src/components/forms/AccountAction/accountAction.jsx

Changed the order of buttons in the main menu and changed two icons.

feat: rename reorder buttons

---

.vscode/settings.json
desktop/jest.config.js
desktop/package.json
desktop/pnpm-lock.yaml
desktop/src/containers/Clock/clockOutContainer.tsx
desktop/src/containers/Shift/shiftCRUD.container.jsx
desktop/src/helpers/shiftDuration.test.ts
desktop/src/helpers/shiftDuration.ts
desktop/src/helpers/time.test.ts
desktop/src/helpers/time.ts
desktop/src/store/Shift/actions.ts
desktop/tsconfig.json

-Fixed the bug where Time Left was showing 0:15 in Admin View of Shifts
-The bug was the result of Admin view and Employee view counting shift length differently (emp view counted secs, adm view did not)
-With this code, all shift lengths are counted consistently, with seconds (7:29 mins is rounded to 0 mins, 7:30 is rounded to 15 mins)
-Added a few tests for the `getShiftDuration` function

fix: consistent implementation for shift duration

---

desktop/src/components/tables/Table/styles.jsx
desktop/src/components/tables/Table/table.jsx
desktop/src/index.jsx

Added better highlight in admin view

feat: better highlight

---

desktop/src/components/forms/AccountAction/accountAction.jsx
desktop/src/containers/Analyze/authorityDetailContainer.jsx
desktop/src/containers/Employee/employeeCRUD.container.jsx
desktop/src/containers/Task/taskToolbar.container.jsx
desktop/src/helpers/withMediaQuery.jsx
desktop/src/scenes/Analyze/analyze.jsx

Added hamburger menu to admin toolbar in mobile view

feat: mobile friendly toolbar

---

desktop/src/scenes/Analyze/analyze.jsx

Edited the export logo in Admin view to the old one (Storage)

fix: added the old export icon

---

api/lb3app/server/server.js
desktop/src/components/forms/Shift/HalfShift/halfShift.jsx
desktop/src/containers/Clock/clockOutContainer.tsx
desktop/src/containers/Shift/shiftCRUD.container.tsx

Reverting previous PR #156 to investigate a production issue.

fix: revert use clock-out date from backend

---

desktop/src/components/forms/Shift/FormHeader/formHeader.jsx
desktop/src/components/forms/Shift/FormHeader/styles.jsx
desktop/src/components/forms/Shift/FullShift/styles.jsx
desktop/src/components/forms/Shift/HalfShift/halfShift.jsx
desktop/src/components/forms/Shift/HalfShift/styles.jsx
desktop/src/components/inputs/Time/styles.jsx
desktop/src/components/inputs/Time/time.jsx
desktop/src/components/inputs/TypeableTime/time.jsx
desktop/src/components/layouts/Hero/styles.jsx
desktop/src/components/utils/getHelperText.ts
desktop/src/scenes/Analyze/analyze.jsx

feat: shifts page mobile friendly

---

desktop/src/components/forms/Shift/Filter/filter.jsx
desktop/src/containers/Shift/shiftFilter.container.jsx

On Shifts page in Admin view, Filter dropdown only filters by Date, no Time (hrs/mins/secs)

feat: shifts filter by date only

---

.vscode/settings.json
api/lb3app/common/models/employee.js
api/lb3app/common/models/helpers.js
desktop/src/components/forms/AccountSigin/accountSigin.tsx

Scheduled clock-in, backend part

feat(api): scheduled clock-in support

---

desktop/public/electron.js

Added a dev tools debugger for electron app (console.logs are visible now)

electron dev tools debugger added

---

desktop/src/store/Shift/selectors.jsx

**Issue:** Random Export behavior
**Reproduce:**
Log into the electron app
Press Export
Export for the range of dates that DOES NOT have shifts
Gets 'Export Failed' message
Then, go back to main menu and select Crew or Admin
Go back to main menu and select Export again
For the same dates range, you get Export Success
**Video:**
https://github.com/user-attachments/assets/2a9d750c-94ee-46db-bd60-b29dfebbadd1
**Temporary Fix:**
One liner that allows for excel export to be completed even if there were no shifts in the time period

export failed bug temporary fix

---

desktop/package.json

Updating package with new version 3.0.44

chore: release 3.0.44 version update

---

desktop/package.json

Update package.json with version 3.0.45

chore: release 3.0.45 version update

---

desktop/public/electron.js

Adds version to electron window title:

feat: show version in electron window title

---

desktop/package.json

chore: release 3.0.46

---

desktop/src/components/forms/Employee/employee.jsx
desktop/src/containers/Shift/shiftFilter.container.jsx
desktop/src/scenes/Analyze/analyze.jsx

-Fix: shifts filter by same day works again
-Fix: shifts tab in admin opens by default again
-Fix: removed pin generator from employee filter

Filter-related fixes

---

desktop/package.json

Version updated in package.json to 3.0.47

chore: release 3.0.47

---

desktop/src/containers/Employee/employeeIndex.container.jsx

-in Employees, added a column on the left side that displays ee number of employees, with a functioning sort

employee ee number sort

---

desktop/package.json

updated readme instructions for release

chore: release 3.0.48
